import html_to_json

html_string = """
<body>
<img style="position:absolute;top:0.00in;left:0.00in;width:9.02in;height:29.70in" src="ci_1.png" />
<img style="position:absolute;top:0.00in;left:0.00in;width:9.02in;height:29.70in" src="ci_2.png" />
<img style="position:absolute;top:0.10in;left:3.01in;width:6.26in;height:29.60in" src="ci_3.png" />
<img style="position:absolute;top:1.02in;left:3.01in;width:6.26in;height:0.02in" src="ci_4.png" />
<img style="position:absolute;top:5.93in;left:3.92in;width:3.39in;height:0.25in" src="ci_5.png" />
<img style="position:absolute;top:5.93in;left:7.31in;width:1.03in;height:0.25in" src="ci_6.png" />
<a href="http://click.lowes.com/f/a/Vpwt9IYiSPBlzK0ftk6pPw~~/AAQrWwA~/RgRlgxcQP0QWaHR0cHM6Ly93d3cubG93ZXMuY29tL1cDc3BjQgpjkBCSoGPaA59LUhJ3b29keUB2aWJlY29kZS52aXBYBAAAAAA~"><img style="position:absolute;top:0.35in;left:5.61in;width:1.04in;height:0.49in" src="ri_1.png" />
</a><div style="position:absolute;top:1.38in;left:4.72in;width:2.92in;line-height:0.41in;"><span style="font-style:normal;font-weight:bold;font-size:19pt;font-family:Liberation Sans;color:#333333">Your Lowe&apos;s Receipt</span><span style="font-style:normal;font-weight:bold;font-size:19pt;font-family:Liberation Sans;color:#333333"> </span><br/></SPAN></div>
<div style="position:absolute;top:1.99in;left:3.44in;width:5.44in;line-height:0.21in;"><span style="font-style:normal;font-weight:normal;font-size:10pt;font-family:Liberation Sans;color:#333333">Thanks for shopping at Lowe&apos;s. Use this just like you would a paper receipt for</span><span style="font-style:normal;font-weight:normal;font-size:10pt;font-family:Liberation Sans;color:#333333"> </span><br/><DIV style="position:relative; left:0.87in;"><span style="font-style:normal;font-weight:normal;font-size:10pt;font-family:Liberation Sans;color:#333333">proof of purchase, record keeping, returns and more.</span><span style="font-style:normal;font-weight:normal;font-size:10pt;font-family:Liberation Sans;color:#333333"> </span><br/></SPAN></DIV></div>
<div style="position:absolute;top:2.83in;left:5.06in;width:2.19in;line-height:0.20in;"><span style="font-style:normal;font-weight:bold;font-size:9pt;font-family:Liberation Sans;color:#333333">LOWE&apos;S HOME CENTERS, LLC</span><span style="font-style:normal;font-weight:bold;font-size:9pt;font-family:Liberation Sans;color:#333333"> </span><br/><DIV style="position:relative; left:0.20in;"><span style="font-style:normal;font-weight:bold;font-size:9pt;font-family:Liberation Sans;color:#333333">13000 Gateway Center Dr</span><span style="font-style:normal;font-weight:bold;font-size:9pt;font-family:Liberation Sans;color:#333333"> </span><br/></SPAN></DIV><DIV style="position:relative; left:0.31in;"><span style="font-style:normal;font-weight:bold;font-size:9pt;font-family:Liberation Sans;color:#333333">Gainesville , VA 20155</span><span style="font-style:normal;font-weight:bold;font-size:9pt;font-family:Liberation Sans;color:#333333"> </span><br/></DIV><DIV style="position:relative; left:0.58in;"><span style="font-style:normal;font-weight:bold;font-size:9pt;font-family:Liberation Sans;color:#0471af">(703) 468-6000</span><span style="font-style:normal;font-weight:bold;font-size:9pt;font-family:Liberation Sans;color:#0471af"> </span><br/></SPAN></DIV></div>
<img style="position:absolute;top:3.87in;left:3.92in;width:4.42in;height:0.01in" src="ci_7.png" />
<div style="position:absolute;top:4.16in;left:3.92in;width:2.36in;line-height:0.19in;"><span style="font-style:normal;font-weight:normal;font-size:9pt;font-family:Liberation Sans;color:#333333">Transaction # : 674793202</span><span style="font-style:normal;font-weight:normal;font-size:9pt;font-family:Liberation Sans;color:#333333"> </span><br/></SPAN><span style="font-style:normal;font-weight:normal;font-size:9pt;font-family:Liberation Sans;color:#333333">Order # : 202212191870674793202</span><span style="font-style:normal;font-weight:normal;font-size:9pt;font-family:Liberation Sans;color:#333333"> </span><br/><span style="font-style:normal;font-weight:normal;font-size:9pt;font-family:Liberation Sans;color:#333333">Order Date : 12/19/22 11:32:15</span><span style="font-style:normal;font-weight:normal;font-size:9pt;font-family:Liberation Sans;color:#333333"> </span><br/></SPAN></div>
<img style="position:absolute;top:4.95in;left:3.92in;width:4.42in;height:0.01in" src="ci_8.png" />
<img style="position:absolute;top:5.22in;left:4.31in;width:3.65in;height:0.37in" src="ri_2.png" />
<div style="position:absolute;top:5.97in;left:4.03in;width:0.34in;line-height:0.21in;"><span style="font-style:normal;font-weight:bold;font-size:9pt;font-family:Liberation Sans;color:#333333">Item</span><span style="font-style:normal;font-weight:bold;font-size:9pt;font-family:Liberation Sans;color:#333333"> </span><br/></SPAN></div>
<div style="position:absolute;top:5.97in;left:7.89in;width:0.40in;line-height:0.21in;"><span style="font-style:normal;font-weight:bold;font-size:9pt;font-family:Liberation Sans;color:#333333">Price</span><span style="font-style:normal;font-weight:bold;font-size:9pt;font-family:Liberation Sans;color:#333333"> </span><br/></SPAN></div>
<div style="position:absolute;top:6.49in;left:4.03in;width:2.18in;line-height:0.19in;"><span style="font-style:normal;font-weight:normal;font-size:9pt;font-family:Liberation Sans;color:#333333">CM 25-PC SCREWDRIVING BIT</span><span style="font-style:normal;font-weight:normal;font-size:9pt;font-family:Liberation Sans;color:#333333"> </span><br/></SPAN></div>
<div style="position:absolute;top:6.60in;left:7.76in;width:0.53in;line-height:0.19in;"><span style="font-style:normal;font-weight:normal;font-size:9pt;font-family:Liberation Sans;color:#333333">$ 13.98</span><span style="font-style:normal;font-weight:normal;font-size:9pt;font-family:Liberation Sans;color:#333333"> </span><br/></SPAN></div>
<div style="position:absolute;top:6.90in;left:4.24in;width:1.10in;line-height:0.19in;"><span style="font-style:normal;font-weight:normal;font-size:9pt;font-family:Liberation Sans;color:#333333">Item #: 1497097</span><span style="font-style:normal;font-weight:normal;font-size:9pt;font-family:Liberation Sans;color:#333333"> </span><br/></SPAN></div>
<div style="position:absolute;top:7.20in;left:4.24in;width:0.72in;line-height:0.19in;"><span style="font-style:normal;font-weight:normal;font-size:9pt;font-family:Liberation Sans;color:#333333">1 @ 13.98</span><span style="font-style:normal;font-weight:normal;font-size:9pt;font-family:Liberation Sans;color:#333333"> </span><br/></SPAN></div>
<div style="position:absolute;top:7.81in;left:4.03in;width:2.11in;line-height:0.19in;"><span style="font-style:normal;font-weight:normal;font-size:9pt;font-family:Liberation Sans;color:#333333">FEIT 20W MR16 XENON GU10</span><span style="font-style:normal;font-weight:normal;font-size:9pt;font-family:Liberation Sans;color:#333333"> </span><br/></SPAN></div>
<div style="position:absolute;top:7.91in;left:7.76in;width:0.53in;line-height:0.19in;"><span style="font-style:normal;font-weight:normal;font-size:9pt;font-family:Liberation Sans;color:#333333">$ 25.96</span><span style="font-style:normal;font-weight:normal;font-size:9pt;font-family:Liberation Sans;color:#333333"> </span><br/></SPAN></div>
<div style="position:absolute;top:8.22in;left:4.24in;width:1.02in;line-height:0.19in;"><span style="font-style:normal;font-weight:normal;font-size:9pt;font-family:Liberation Sans;color:#333333">Item #: 140430</span><span style="font-style:normal;font-weight:normal;font-size:9pt;font-family:Liberation Sans;color:#333333"> </span><br/></SPAN></div>
<div style="position:absolute;top:8.52in;left:4.24in;width:0.72in;line-height:0.19in;"><span style="font-style:normal;font-weight:normal;font-size:9pt;font-family:Liberation Sans;color:#333333">2 @ 12.98</span><span style="font-style:normal;font-weight:normal;font-size:9pt;font-family:Liberation Sans;color:#333333"> </span><br/></SPAN></div>
<div style="position:absolute;top:9.12in;left:4.03in;width:2.08in;line-height:0.19in;"><span style="font-style:normal;font-weight:normal;font-size:9pt;font-family:Liberation Sans;color:#333333">124-FL OZ ULTRA SEMI UW/B</span><span style="font-style:normal;font-weight:normal;font-size:9pt;font-family:Liberation Sans;color:#333333"> </span><br/></SPAN></div>
<div style="position:absolute;top:9.23in;left:7.76in;width:0.53in;line-height:0.19in;"><span style="font-style:normal;font-weight:normal;font-size:9pt;font-family:Liberation Sans;color:#333333">$ 39.98</span><span style="font-style:normal;font-weight:normal;font-size:9pt;font-family:Liberation Sans;color:#333333"> </span><br/></SPAN></div>
<div style="position:absolute;top:9.53in;left:4.24in;width:1.02in;line-height:0.19in;"><span style="font-style:normal;font-weight:normal;font-size:9pt;font-family:Liberation Sans;color:#333333">Item #: 935300</span><span style="font-style:normal;font-weight:normal;font-size:9pt;font-family:Liberation Sans;color:#333333"> </span><br/></SPAN></div>
<div style="position:absolute;top:9.83in;left:4.24in;width:0.72in;line-height:0.19in;"><span style="font-style:normal;font-weight:normal;font-size:9pt;font-family:Liberation Sans;color:#333333">1 @ 39.98</span><span style="font-style:normal;font-weight:normal;font-size:9pt;font-family:Liberation Sans;color:#333333"> </span><br/></SPAN></div>
<div style="position:absolute;top:10.44in;left:4.03in;width:1.96in;line-height:0.19in;"><span style="font-style:normal;font-weight:normal;font-size:9pt;font-family:Liberation Sans;color:#333333">CM V20 MAX 1/2-IN DRILL/D</span><span style="font-style:normal;font-weight:normal;font-size:9pt;font-family:Liberation Sans;color:#333333"> </span><br/></SPAN></div>
<div style="position:absolute;top:10.54in;left:7.76in;width:0.53in;line-height:0.19in;"><span style="font-style:normal;font-weight:normal;font-size:9pt;font-family:Liberation Sans;color:#333333">$ 59.00</span><span style="font-style:normal;font-weight:normal;font-size:9pt;font-family:Liberation Sans;color:#333333"> </span><br/></SPAN></div>
<div style="position:absolute;top:10.84in;left:4.24in;width:1.10in;line-height:0.19in;"><span style="font-style:normal;font-weight:normal;font-size:9pt;font-family:Liberation Sans;color:#333333">Item #: 1033800</span><span style="font-style:normal;font-weight:normal;font-size:9pt;font-family:Liberation Sans;color:#333333"> </span><br/></SPAN></div>
<div style="position:absolute;top:11.15in;left:4.24in;width:0.72in;line-height:0.19in;"><span style="font-style:normal;font-weight:normal;font-size:9pt;font-family:Liberation Sans;color:#333333">1 @ 59.00</span><span style="font-style:normal;font-weight:normal;font-size:9pt;font-family:Liberation Sans;color:#333333"> </span><br/></SPAN></div>
<div style="position:absolute;top:11.55in;left:4.24in;width:1.62in;line-height:0.21in;"><span style="font-style:normal;font-weight:bold;font-size:9pt;font-family:Liberation Sans;color:#333333">Invoice 82323 Subtotal</span><span style="font-style:normal;font-weight:bold;font-size:9pt;font-family:Liberation Sans;color:#333333"> </span><br/></SPAN></div>
<div style="position:absolute;top:11.55in;left:7.67in;width:0.61in;line-height:0.19in;"><span style="font-style:normal;font-weight:normal;font-size:9pt;font-family:Liberation Sans;color:#333333">$ 138.92</span><span style="font-style:normal;font-weight:normal;font-size:9pt;font-family:Liberation Sans;color:#333333"> </span><br/></SPAN></div>
<img style="position:absolute;top:12.00in;left:3.92in;width:4.42in;height:0.01in" src="ci_9.png" />
<div style="position:absolute;top:12.28in;left:4.44in;width:1.62in;line-height:0.21in;"><span style="font-style:normal;font-weight:bold;font-size:9pt;font-family:Liberation Sans;color:#333333">Invoice 82323 Subtotal</span><span style="font-style:normal;font-weight:bold;font-size:9pt;font-family:Liberation Sans;color:#333333"> </span><br/></SPAN></div>
<div style="position:absolute;top:12.28in;left:7.67in;width:0.61in;line-height:0.19in;"><span style="font-style:normal;font-weight:normal;font-size:9pt;font-family:Liberation Sans;color:#333333">$ 138.92</span><span style="font-style:normal;font-weight:normal;font-size:9pt;font-family:Liberation Sans;color:#333333"> </span><br/></SPAN></div>
</body>
"""
output_json = html_to_json.convert_html.convert(html_string)
print(output_json)